### ISSUE TITLE
Stacked Bar Graph

### ISSUE THREAD

**Issue by tobycoder** [vanatteveldt/rpuzzles#1]
Heb een stacked bar graph nodig! Data kan ik niet toesturen ivm NDA, maar heb een data frame met een var1: 12345, Freq: numeriek, en Per: percentages met een som van 100.

**Comment by kasperwelbers** [comment]
Je mist nog een kolom :).

Je moet een categorie voor de x as en 1 om te stacken. Bijv:

d = data.frame(wine = c(rep('Gigondas', 3), rep('Pomerol',2)),
               grape = c('Grenache','Syrah','Mourvedre', 'Merlot','Cabernet Franc'),
               pct = c(80, 5,15, 75,25))

d
library(ggplot2)
ggplot(d, aes(x = wine, y = pct, fill = grape)) + 
  geom_bar(stat = "identity")

**Comment by tobycoder** [comment]
Yes Yes Yes!! Thanks hij doet het!!!

**Comment by kasperwelbers** [comment]
Dan verklaar ik bij deze de eerste R puzzle gesloten! :)

**Comment by vanatteveldt** [comment]
Feest! :)

Probeer in het vervolg wel om een dataset erbij te zetten, desnoods een testdatasetje, en de code die je al had geprobeerd. Dat maakt het veel nuttiger voor iemand die het leest.
